[package]
name = "sigmatui"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.1"
ratzilla = "0.0.4"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["Clipboard", "Navigator"] }
